version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nurseshift-postgres
    environment:
      POSTGRES_DB: nurseshift
      POSTGRES_USER: nurseshift_user
      POSTGRES_PASSWORD: nurseshift_pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    networks:
      - nurseshift-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nurseshift_user -d nurseshift"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: nurseshift-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nurseshift-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: nurseshift-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nurseshift.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - nurseshift-network
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

networks:
  nurseshift-network:
    driver: bridge

